In [2]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
# dictionary와 유사한 Bunch 클래스의 형태이다.
# 키와 값으로 구성돼있다.

In [3]:
print("iris_dataset의 키:\n",iris_dataset.keys())
# DESCR 키에는 데이터셋에 대한 간략한 설명이 들어있다.

iris_dataset의 키:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
print("타깃의 이름:",iris_dataset['target_names'])
# 예측하려는 붓꽃 품종의 이름을 문자열 배열로 가지고 있다.

타깃의 이름: ['setosa' 'versicolor' 'virginica']


In [5]:
print("특성의 이름:\n",iris_dataset['feature_names'])
# 각 특성을 설명하는 문자열 리스트이다.

특성의 이름:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print("data의 타입:",type(iris_dataset['data']))
# 개개의 꽃이 되며 열은 각 꽃에서 구한 네 개의 측정치이다.

data의 타입: <class 'numpy.ndarray'>


In [7]:
print("data의 크기:",iris_dataset['data'].shape)
# 150개의 붓꽃 데이터를 가지고 있다.
# 각 아이템을 샘플이라고 부르며, 속성은 특성이라고 부른다.

data의 크기: (150, 4)


In [8]:
print("data의 처음 다섯 행:\n",iris_dataset['data'][:5])

data의 처음 다섯 행:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [9]:
print("target의 타입:",type(iris_dataset['target']))

target의 타입: <class 'numpy.ndarray'>


In [10]:
print("target의 크기:",iris_dataset['target'].shape)

target의 크기: (150,)


In [11]:
print("타깃:\n",iris_dataset['target'])
# 붓꽃의 종류는 0에서 2까지의 정수로 기록되어 있습니다.

타깃:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
